INSERT INTO rolle VALUES(1,'ROLE_ADMIN');
INSERT INTO rolle VALUES(2,'ROLE_RECRUITER');
INSERT INTO rolle VALUES(3,'ROLE_COM_MANAGER');
INSERT INTO rolle VALUES(4,'ROLE_MANAGER');
INSERT INTO rolle VALUES(5,'ROLE_STUDENT');


